### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'inputs'

### ISSUE THREAD

**Issue by adarshbhandaryp** [rdevon/DIM#15] opened 2019-04-29 20:05 UTC
Hi, 

I am getting this error when trying to run the code.   

File "scripts/main.py", line 65, in <module>
    controller = Controller(inputs=dict(inputs='data.images'), **models)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\cortex_DIM\models\controller.py", line 126, in __init__
    super().__init__(inputs=inputs)
TypeError: __init__() got an unexpected keyword argument 'inputs'

Best

**Comment by rdevon** [comment] 2019-04-30 02:28
I'm a little unsure what I'm looking at because `__init__` is being replaced with `init`, but I suspect that you didn't install cortex or DIM correctly. Can you confirm that you are using the right version of cortex by running `python -c "import cortex; print(cortex.__version__)"`?

How did you install cortex and DIM?

**Comment by rdevon** [comment] 2019-05-01 11:11
Did you sort this out?

**Comment by rdevon** [comment] 2019-05-02 12:39
Closing as I'm fairly certain this is due to not installing cortex or DIM properly.

**Closed as completed by rdevon** 2019-05-02 12:39 UTC

**Comment by adarshbhandaryp** [comment] 2019-05-02 22:57
Hi,

I had installed the wrong version of cortex. It works fine now ! 

Thanks :)

**Comment by SkyeLu** [comment] 2019-07-26 14:03
Hi, I installed cortex following structions in [this link](https://github.com/rdevon/cortex), but I got the same error `TypeError: init() got an unexpected keyword argument 'inputs'.` When I run `print(cortex.__version__)` , it says that `AttributeError: module 'cortex' has no attribute '__version__'
`
I don't know what goes wrong. Could you help me? @rdevon

**Comment by bybike1** [comment] 2023-02-16 08:07
I have same issue.
I may incorrect the version of cortex.
But I don't know how to install cortex you expected version.
How could you reproduce your environment?
